<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="ru" xml:lang="ru">
<head>
<link rel="icon" href="http://bladeforum.ru/favicon.ico" type="image/x-icon">
<link rel="shortcut icon" href="http://bladeforum.ru/favicon.ico" type="image/x-icon">

<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="content-style-type" content="text/css" />
<meta http-equiv="content-language" content="ru" />
<meta http-equiv="imagetoolbar" content="no" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<meta name="keywords" content="" />
<meta name="description" content="" />

<title>Санкт-Петербургский ножевой Клуб &bull; Главная страница</title>
<!-- // MOD : MSSTI RSS Feeds (V1.0.9) - Start-->
<link rel="alternate" type="application/rss+xml" title="{ RSS_FEEDS } - Санкт-Петербургский ножевой Клуб" href="http://bladeforum.ru/rss.php" />
<link rel="alternate" type="application/rss+xml" title="{ RSS_FEEDS } - Все форумы" href="http://bladeforum.ru/rss.php?mode=forums" /><link rel="alternate" type="application/rss+xml" title="{ RSS_FEEDS } - Все темы" href="http://bladeforum.ru/rss.php?mode=topics" /><link rel="alternate" type="application/rss+xml" title="{ RSS_FEEDS } - Все сообщения" href="http://bladeforum.ru/rss.php?mode=posts" /><!-- // MOD : MSSTI RSS Feeds (V1.0.9) - End -->


<!--
	phpBB style name: prosilver
	Based on style:   prosilver (this is the default phpBB3 style)
	Original author:  Tom Beddard ( http://www.subBlue.com/ )
	Modified by:      

<link rel="alternate" type="application/atom+xml" title="Канал - Санкт-Петербургский ножевой Клуб" href="http://bladeforum.ru/feed.php" /><link rel="alternate" type="application/atom+xml" title="Канал - Все форумы" href="http://bladeforum.ru/feed.php?mode=forums" />

	NOTE: This page was generated by phpBB, the free open-source bulletin board package.
	      The phpBB Group is not responsible for the content of this page and forum. For more information
	      about phpBB please visit http://www.phpbb.com
-->

<script type="text/javascript">
// <![CDATA[


function popup(url, width, height, name)
{
	if (!name)
	{
		name = '_popup';
	}

	window.open(url.replace(/&amp;/g, '&'), name, 'height=' + height + ',resizable=yes,scrollbars=yes,width=' + width);
	return false;
}

function jumpto()
{
	var page = prompt('Введите номер страницы, на которую хотите перейти:', '');
	var per_page = '';
	var base_url = '';
	var style_cookie = 'phpBBstyle';
	var style_cookie_settings = '; path=/; domain=.bladeforum.ru';
	var onload_functions = new Array();
	var onunload_functions = new Array();

	if (page !== null && !isNaN(page) && page == Math.floor(page) && page > 0)
	{
		if (base_url.indexOf('?') == -1)
		{
			document.location.href = base_url + '?start=' + ((page - 1) * per_page);
		}
		else
		{
			document.location.href = base_url.replace(/&amp;/g, '&') + '&start=' + ((page - 1) * per_page);
		}
	}
}

/**
* Find a member
*/
function find_username(url)
{
	popup(url, 760, 570, '_usersearch');
	return false;
}

/**
	* New function for handling multiple calls to window.onload and window.unload by pentapenguin
*/
	window.onload = function()
{
		for (var i = 0; i < onload_functions.length; i++)
	{
			eval(onload_functions[i]);
                        return false;
	}
	}

	window.onunload = function()
	{
		for (var i = 0; i < onunload_functions.length; i++)
		{
			eval(onunload_functions[i]);
	}
}

// ]]>
</script>


<link href="./styles/subsilver2/theme/stylesheet.css" rel="stylesheet" type="text/css" media="screen, projection" />


<script type="text/javascript">

	function countAdClick(id)
	{
	   loadXMLDoc('./ads/click.php?a=' + id);
	}

	function countAdView(id)
	{
	   loadXMLDoc('./ads/view.php?a=' + id);
	}

	function loadXMLDoc(url) {
	   req = false;
	   if(window.XMLHttpRequest) {
	      try {
	         req = new XMLHttpRequest();
	      } catch(e) {
	         req = false;
	      }
	   } else if(window.ActiveXObject) {
	      try {
	         req = new ActiveXObject("Msxml2.XMLHTTP");
	      } catch(e) {
	         try {
	            req = new ActiveXObject("Microsoft.XMLHTTP");
	         } catch(e) {
	            req = false;
	         }
	      }
	   }
	   if(req) {
	      req.open("GET", url, true);
	      req.send(null);
	   }
	}
</script>
</head>

<body id="phpbb" class="section-index ltr">

<div id="wrap">
	
	<a id="top" name="top" accesskey="t"></a>
	<div id="page-header">
		<div class="headerbar">
			<div class="inner"><span class="corners-top"><span></span></span>

		<table width="100%" cellspacing="0">
		<tr>
			<td><a href="http://bladeforum.ru"><img src="./styles/subsilver2/imageset/site_logo.gif" width="200" height="121" alt="" title="" /></a></td>
			<td width="100%" align="center"><h1>Санкт-Петербургский ножевой Клуб</h1><span class="gen"><a href="http://bladeforum.ru"><p></p></a></span></td>
		</tr>
		</table>


<!--ererfref------>
	<div id="menubar">
		<table width="100%" cellspacing="0">
		<tr>
			<td class="genmed">
				<a href="./ucp.php?mode=login&amp;sid=32e897f27680334ea0085fb7ace65864"><img src="./styles/subsilver2/theme/images/icon_mini_login.gif" width="12" height="13" alt="*" /> Вход</a>&nbsp; &nbsp;<a href="./ucp.php?mode=register&amp;sid=32e897f27680334ea0085fb7ace65864"><img src="./styles/subsilver2/theme/images/icon_mini_register.gif" width="12" height="13" alt="*" /> Регистрация</a>
					
			</td>
			<td class="genmed" align="right">
				<a href="./faq.php?sid=32e897f27680334ea0085fb7ace65864"><img src="./styles/subsilver2/theme/images/icon_mini_faq.gif" width="12" height="13" alt="*" /> FAQ</a>
				&nbsp; &nbsp;<a href="./search.php?sid=32e897f27680334ea0085fb7ace65864"><img src="./styles/subsilver2/theme/images/icon_mini_search.gif" width="12" height="13" alt="*" /> Поиск</a>
			</td>
		</tr>
		</table>
	</div>

	<div id="datebar">
		<table width="100%" cellspacing="0">
		<tr>
			<td class="gensmall"></td>
			<td class="gensmall" align="right">Текущее время: Вс ноя 09, 2014 23:54<br /></td>
		</tr>
		</table>
	</div>

</div>
<table width="100%" height="100%" border="0" cellpadding="7" cellspacing="2" >
<tr>
<td width="50%" align="center">
<center>
<a href=http://www.kizlyarextreme.ru/nozhi-kizlyar-supreme> 
<object type="application/x-shockwave-flash" data="banners/kizlyar400_90.swf" width="400" height="90" id="left_ban" align="middle">
<param name="allowScriptAccess" value="sameDomain" />
<param name="movie" value="banners/kizlyar400_90.swf" />
<param name="quality" value="high" />
<param name="bgcolor" value="#ffffff" />
</object> 
</a> 
</center>
</td>


<td colspan="3" width="50%" align="center">
<a href="http://brutalica.ru"><img src="banners/brutalica400x90.gif" border="0"> </a>
</td>
</tr>
</table><br />
<div id="wrapcentre">

	
	<p class="searchbar">
		<span style="float: left;"><a href="./search.php?search_id=unanswered&amp;sid=32e897f27680334ea0085fb7ace65864">Сообщения без ответов</a> | <a href="./search.php?search_id=active_topics&amp;sid=32e897f27680334ea0085fb7ace65864">Активные темы</a></span>
		
	</p>
	

	<br style="clear: both;" />

	<table class="tablebg" width="100%" cellspacing="1" cellpadding="0" style="margin-top: 5px;">
	<tr>
		<td class="row1">
			<p class="breadcrumbs"><a href="./index.php?sid=32e897f27680334ea0085fb7ace65864">Список форумов</a></p>
			<p class="datetime">Часовой пояс: UTC + 3 часа [ Летнее время ]</p>
		</td>
	</tr>
	</table>

	<br />
<!--ererfref------><table class="tablebg" cellspacing="1" width="100%">
<tr>
	<td class="cat" colspan="5" align="right">&nbsp;</td>
</tr>
<tr>
	<th colspan="2">&nbsp;Форум&nbsp;</th>
	<th width="50">&nbsp;Темы&nbsp;</th>
	<th width="50">&nbsp;Сообщения&nbsp;</th>
	<th>&nbsp;Последнее сообщение&nbsp;</th>
</tr>

		<tr>
			<td class="cat" colspan="2"><h4><a href="./viewforum.php?f=7&amp;sid=32e897f27680334ea0085fb7ace65864">Ножевые форумы</a></h4></td>
			<td class="catdiv" colspan="3">&nbsp;</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=1&amp;sid=32e897f27680334ea0085fb7ace65864">Про ножи</a>
				<p class="forumdesc">приглашаются все любители ножей...</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">449</p></td>
			<td class="row2" align="center"><p class="topicdetails">19199</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Вс ноя 09, 2014 22:29</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=5388&amp;sid=32e897f27680334ea0085fb7ace65864">Shah</a>
						<a href="./viewtopic.php?f=1&amp;p=146442&amp;sid=32e897f27680334ea0085fb7ace65864#p146442"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=13&amp;sid=32e897f27680334ea0085fb7ace65864">Обзоры</a>
				<p class="forumdesc">Обзоры наших участников. Про ножи, про инструменты, про все, что интересно</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">172</p></td>
			<td class="row2" align="center"><p class="topicdetails">4155</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Вс ноя 09, 2014 23:49</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>
						<a href="./viewtopic.php?f=13&amp;p=146468&amp;sid=32e897f27680334ea0085fb7ace65864#p146468"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=6&amp;sid=32e897f27680334ea0085fb7ace65864">Мастерская</a>
				<p class="forumdesc">Здесь пишется все, что касается изготовления ножей своими руками, новые конструкции, замки, технологии</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">1269</p></td>
			<td class="row2" align="center"><p class="topicdetails">23363</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Вс ноя 09, 2014 23:52</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=9352&amp;sid=32e897f27680334ea0085fb7ace65864">кинолог</a>
						<a href="./viewtopic.php?f=6&amp;p=146472&amp;sid=32e897f27680334ea0085fb7ace65864#p146472"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=47&amp;sid=32e897f27680334ea0085fb7ace65864">Производители</a>
				<p class="forumdesc">производители ножей, ножен, фурнитуры</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">8</p></td>
			<td class="row2" align="center"><p class="topicdetails">199</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Вс сен 14, 2014 15:42</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=16038&amp;sid=32e897f27680334ea0085fb7ace65864">bozman</a>
						<a href="./viewtopic.php?f=47&amp;p=137752&amp;sid=32e897f27680334ea0085fb7ace65864#p137752"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=34&amp;sid=32e897f27680334ea0085fb7ace65864">Историческое холодное оружие</a>
				<p class="forumdesc">Здесь беседуют о любом историческом холодном оружии</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">39</p></td>
			<td class="row2" align="center"><p class="topicdetails">550</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Вт окт 28, 2014 23:11</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=9216&amp;sid=32e897f27680334ea0085fb7ace65864">Andrzej</a>
						<a href="./viewtopic.php?f=34&amp;p=144377&amp;sid=32e897f27680334ea0085fb7ace65864#p144377"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=36&amp;sid=32e897f27680334ea0085fb7ace65864">Кастомные ножи</a>
				<p class="forumdesc">Они - высшая лига среди ножей. Обсуждение, восхищение</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">27</p></td>
			<td class="row2" align="center"><p class="topicdetails">424</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Ср ноя 05, 2014 17:04</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=17843&amp;sid=32e897f27680334ea0085fb7ace65864">mosby</a>
						<a href="./viewtopic.php?f=36&amp;p=145547&amp;sid=32e897f27680334ea0085fb7ace65864#p145547"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=9&amp;sid=32e897f27680334ea0085fb7ace65864">Изобретения и хорошие идеи</a>
				<p class="forumdesc">Идеи и разработки, не только участников форума, но и увиденные в интернете</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">42</p></td>
			<td class="row2" align="center"><p class="topicdetails">713</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Пт окт 31, 2014 0:53</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=17042&amp;sid=32e897f27680334ea0085fb7ace65864">barada</a>
						<a href="./viewtopic.php?f=9&amp;p=144736&amp;sid=32e897f27680334ea0085fb7ace65864#p144736"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=52&amp;sid=32e897f27680334ea0085fb7ace65864">Все про заточку</a>
				<p class="forumdesc">Точильные устройства и приспособления, приемы заточки и советы опытных людей</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">34</p></td>
			<td class="row2" align="center"><p class="topicdetails">653</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Вт окт 28, 2014 21:20</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=16407&amp;sid=32e897f27680334ea0085fb7ace65864">failbot</a>
						<a href="./viewtopic.php?f=52&amp;p=144333&amp;sid=32e897f27680334ea0085fb7ace65864#p144333"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=37&amp;sid=32e897f27680334ea0085fb7ace65864">Мультитулы, топоры, шанцевый инструмент</a>
				<p class="forumdesc">обсуждаем мультитулы, топоры, шанцевый инструмент, все, что не очень подходит под понятие &quot;ножи&quot;</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">33</p></td>
			<td class="row2" align="center"><p class="topicdetails">852</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Вс ноя 09, 2014 2:01</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=3993&amp;sid=32e897f27680334ea0085fb7ace65864">Angry Zeka</a>
						<a href="./viewtopic.php?f=37&amp;p=146316&amp;sid=32e897f27680334ea0085fb7ace65864#p146316"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=54&amp;sid=32e897f27680334ea0085fb7ace65864">Книга памяти</a>
				<p class="forumdesc">Про ушедших от нас, но оставивших  заметный след в российском и мировом ножевом мире мастеров</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">11</p></td>
			<td class="row2" align="center"><p class="topicdetails">35</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Вс окт 19, 2014 21:34</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=3282&amp;sid=32e897f27680334ea0085fb7ace65864">Vinny M</a>
						<a href="./viewtopic.php?f=54&amp;p=142796&amp;sid=32e897f27680334ea0085fb7ace65864#p142796"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="cat" colspan="2"><h4><a href="./viewforum.php?f=22&amp;sid=32e897f27680334ea0085fb7ace65864">Кухня</a></h4></td>
			<td class="catdiv" colspan="3">&nbsp;</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=24&amp;sid=32e897f27680334ea0085fb7ace65864">Кухонные ножи и инвентарь</a>
				<p class="forumdesc">обсуждение кухонных ножей и инвентаря</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">52</p></td>
			<td class="row2" align="center"><p class="topicdetails">1151</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Пт окт 31, 2014 12:58</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=17604&amp;sid=32e897f27680334ea0085fb7ace65864">predsedatel7</a>
						<a href="./viewtopic.php?f=24&amp;p=144776&amp;sid=32e897f27680334ea0085fb7ace65864#p144776"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=23&amp;sid=32e897f27680334ea0085fb7ace65864">Рецепты</a>
				<p class="forumdesc">рецепты и техника приготовления блюд</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">54</p></td>
			<td class="row2" align="center"><p class="topicdetails">986</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Пн ноя 03, 2014 23:41</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=7249&amp;sid=32e897f27680334ea0085fb7ace65864">A232K</a>
						<a href="./viewtopic.php?f=23&amp;p=145345&amp;sid=32e897f27680334ea0085fb7ace65864#p145345"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=38&amp;sid=32e897f27680334ea0085fb7ace65864">Сайт А.Козловского cookingknife.ru. Обсуждения</a>
				<p class="forumdesc">Обсуждения материалов с сайта А. Козловского <!-- m --><a class="postlink" href="http://cookingknife.ru" onclick="window.open(this.href);return false;">http://cookingknife.ru</a><!-- m -->, посвященного кухонным ножам, оборудованию и рецептам</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">20</p></td>
			<td class="row2" align="center"><p class="topicdetails">201</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Пт окт 03, 2014 19:56</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=3824&amp;sid=32e897f27680334ea0085fb7ace65864">Teke</a>
						<a href="./viewtopic.php?f=38&amp;p=140129&amp;sid=32e897f27680334ea0085fb7ace65864#p140129"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="cat" colspan="2"><h4><a href="./viewforum.php?f=19&amp;sid=32e897f27680334ea0085fb7ace65864">Торговый ряд</a></h4></td>
			<td class="catdiv" colspan="3">&nbsp;</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read_subforum.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=40&amp;sid=32e897f27680334ea0085fb7ace65864">Ножевые магазины и интернет-магазины</a>
				<p class="forumdesc">Здесь дружественные нашему форуму ножевые магазины и интернет-магазины размещают о себе информацию</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">63</p></td>
			<td class="row2" align="center"><p class="topicdetails">1816</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Вс ноя 09, 2014 13:21</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=3909&amp;sid=32e897f27680334ea0085fb7ace65864">suet@suet</a>
						<a href="./viewtopic.php?f=40&amp;p=146353&amp;sid=32e897f27680334ea0085fb7ace65864#p146353"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=3&amp;sid=32e897f27680334ea0085fb7ace65864">Ножевая барахолка</a>
				<p class="forumdesc">Купля-продажа всего, что относится к тематике, кроме откровенного холодняка. Темы не по теме будут нещадно удаляться!</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">1259</p></td>
			<td class="row2" align="center"><p class="topicdetails">16419</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Вс ноя 09, 2014 23:49</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>
						<a href="./viewtopic.php?f=3&amp;p=146469&amp;sid=32e897f27680334ea0085fb7ace65864#p146469"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=21&amp;sid=32e897f27680334ea0085fb7ace65864">Барахолка ножевой мастерской</a>
				<p class="forumdesc">Купля-продажа всего, что относится к ножеделию. Клинки, материалы, инструменты, точилки и прочее</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">130</p></td>
			<td class="row2" align="center"><p class="topicdetails">1920</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Вс ноя 09, 2014 23:43</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>
						<a href="./viewtopic.php?f=21&amp;p=146463&amp;sid=32e897f27680334ea0085fb7ace65864#p146463"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=11&amp;sid=32e897f27680334ea0085fb7ace65864">Барахолка</a>
				<p class="forumdesc">Купля-продажа всего, не относящегося к ножевой тематике</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">413</p></td>
			<td class="row2" align="center"><p class="topicdetails">4873</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Сб ноя 08, 2014 12:34</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=3159&amp;sid=32e897f27680334ea0085fb7ace65864">Altz</a>
						<a href="./viewtopic.php?f=11&amp;p=146174&amp;sid=32e897f27680334ea0085fb7ace65864#p146174"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=30&amp;sid=32e897f27680334ea0085fb7ace65864">Отзывы о продавцах и покупателях</a>
				<p class="forumdesc">Отзывы о добросовестных или недобросовестных продавцах и покупателях. Глас народа</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">14</p></td>
			<td class="row2" align="center"><p class="topicdetails">311</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Вс сен 21, 2014 0:48</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>
						<a href="./viewtopic.php?f=30&amp;p=138598&amp;sid=32e897f27680334ea0085fb7ace65864#p138598"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="cat" colspan="2"><h4><a href="./viewforum.php?f=15&amp;sid=32e897f27680334ea0085fb7ace65864">Неножевые форумы</a></h4></td>
			<td class="catdiv" colspan="3">&nbsp;</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=12&amp;sid=32e897f27680334ea0085fb7ace65864">Пневматика</a>
				<p class="forumdesc">Все о пневматическом оружии</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">5</p></td>
			<td class="row2" align="center"><p class="topicdetails">152</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Сб ноя 01, 2014 2:48</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=8998&amp;sid=32e897f27680334ea0085fb7ace65864">Корвин</a>
						<a href="./viewtopic.php?f=12&amp;p=144963&amp;sid=32e897f27680334ea0085fb7ace65864#p144963"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=14&amp;sid=32e897f27680334ea0085fb7ace65864">Фонари</a>
				<p class="forumdesc">Про все светящееся и испускающее свет</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">18</p></td>
			<td class="row2" align="center"><p class="topicdetails">630</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Вс ноя 09, 2014 3:25</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=3993&amp;sid=32e897f27680334ea0085fb7ace65864">Angry Zeka</a>
						<a href="./viewtopic.php?f=14&amp;p=146323&amp;sid=32e897f27680334ea0085fb7ace65864#p146323"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=46&amp;sid=32e897f27680334ea0085fb7ace65864">Оптические приборы</a>
				<p class="forumdesc">Бинокли, монокуляры, подзорные трубы, очки, лупы. Обзоры, мнения, советы</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">4</p></td>
			<td class="row2" align="center"><p class="topicdetails">119</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Вс дек 22, 2013 20:29</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=12421&amp;sid=32e897f27680334ea0085fb7ace65864">Loki13</a>
						<a href="./viewtopic.php?f=46&amp;p=101798&amp;sid=32e897f27680334ea0085fb7ace65864#p101798"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=31&amp;sid=32e897f27680334ea0085fb7ace65864">Экипировка и амуниция</a>
				<p class="forumdesc">Про все, что можно назвать экипировкой. И амуницией</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">48</p></td>
			<td class="row2" align="center"><p class="topicdetails">2025</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Пн окт 27, 2014 23:46</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=9260&amp;sid=32e897f27680334ea0085fb7ace65864">Iskander</a>
						<a href="./viewtopic.php?f=31&amp;p=144174&amp;sid=32e897f27680334ea0085fb7ace65864#p144174"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=32&amp;sid=32e897f27680334ea0085fb7ace65864">Часы, телефоны, электроника и гаджеты</a>
				<p class="forumdesc">Обо всем, что звонит, показывает время и отнимает наши деньги</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">49</p></td>
			<td class="row2" align="center"><p class="topicdetails">2083</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Пт окт 31, 2014 0:01</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=3993&amp;sid=32e897f27680334ea0085fb7ace65864">Angry Zeka</a>
						<a href="./viewtopic.php?f=32&amp;p=144708&amp;sid=32e897f27680334ea0085fb7ace65864#p144708"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=33&amp;sid=32e897f27680334ea0085fb7ace65864">Охота и рыбалка</a>
				<p class="forumdesc">Охотники, рыболовы и сочувствующие - вам сюда!</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">36</p></td>
			<td class="row2" align="center"><p class="topicdetails">1387</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Вс ноя 09, 2014 18:36</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=16524&amp;sid=32e897f27680334ea0085fb7ace65864">taranuho.a</a>
						<a href="./viewtopic.php?f=33&amp;p=146378&amp;sid=32e897f27680334ea0085fb7ace65864#p146378"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=51&amp;sid=32e897f27680334ea0085fb7ace65864">Альманах путешествий</a>
				<p class="forumdesc"></p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">40</p></td>
			<td class="row2" align="center"><p class="topicdetails">711</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Ср ноя 05, 2014 17:05</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=17843&amp;sid=32e897f27680334ea0085fb7ace65864">mosby</a>
						<a href="./viewtopic.php?f=51&amp;p=145548&amp;sid=32e897f27680334ea0085fb7ace65864#p145548"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=4&amp;sid=32e897f27680334ea0085fb7ace65864">Просто треп</a>
				<p class="forumdesc">Свободное общение, разговоры на любые темы. Приглашаются все желающие. Поделитесь своими мыслями...</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">996</p></td>
			<td class="row2" align="center"><p class="topicdetails">37347</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Вс ноя 09, 2014 23:51</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=5&amp;sid=32e897f27680334ea0085fb7ace65864" style="color: #AA0000;" class="username-coloured">Михалыч</a>
						<a href="./viewtopic.php?f=4&amp;p=146471&amp;sid=32e897f27680334ea0085fb7ace65864#p146471"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=39&amp;sid=32e897f27680334ea0085fb7ace65864">Встречи и мероприятия</a>
				<p class="forumdesc">Форум о местах встреч форумчан, датах и времени. Нет в мире ничего роскошнее, чем роскошь человеческого общения!</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">79</p></td>
			<td class="row2" align="center"><p class="topicdetails">3855</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Сб ноя 08, 2014 20:05</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>
						<a href="./viewtopic.php?f=39&amp;p=146223&amp;sid=32e897f27680334ea0085fb7ace65864#p146223"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=35&amp;sid=32e897f27680334ea0085fb7ace65864">Технический форум</a>
				<p class="forumdesc">Вопросы, предложения по улучшению работы форума</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">14</p></td>
			<td class="row2" align="center"><p class="topicdetails">1224</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Вс ноя 02, 2014 23:40</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>
						<a href="./viewtopic.php?f=35&amp;p=145243&amp;sid=32e897f27680334ea0085fb7ace65864#p145243"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="cat" colspan="2"><h4><a href="./viewforum.php?f=25&amp;sid=32e897f27680334ea0085fb7ace65864">Поволжская секция</a></h4></td>
			<td class="catdiv" colspan="3">&nbsp;</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=26&amp;sid=32e897f27680334ea0085fb7ace65864">Встречи и мероприятия в Поволжском регионе</a>
				<p class="forumdesc">Встречи и мероприятия в Поволжском регионе</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">46</p></td>
			<td class="row2" align="center"><p class="topicdetails">2406</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Ср окт 29, 2014 22:35</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=11727&amp;sid=32e897f27680334ea0085fb7ace65864">NikSamara</a>
						<a href="./viewtopic.php?f=26&amp;p=144550&amp;sid=32e897f27680334ea0085fb7ace65864#p144550"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=27&amp;sid=32e897f27680334ea0085fb7ace65864">Ножевая барахолка в Поволжском регионе</a>
				<p class="forumdesc">Ножевая барахолка в Поволжском регионе</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">15</p></td>
			<td class="row2" align="center"><p class="topicdetails">285</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Вт авг 26, 2014 23:34</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=4748&amp;sid=32e897f27680334ea0085fb7ace65864">samodelkin8</a>
						<a href="./viewtopic.php?f=27&amp;p=135139&amp;sid=32e897f27680334ea0085fb7ace65864#p135139"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=28&amp;sid=32e897f27680334ea0085fb7ace65864">Неножевая барахолка в Поволжском регионе</a>
				<p class="forumdesc">Неножевая барахолка в Поволжском регионе</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">18</p></td>
			<td class="row2" align="center"><p class="topicdetails">153</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Чт окт 09, 2014 17:43</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=8998&amp;sid=32e897f27680334ea0085fb7ace65864">Корвин</a>
						<a href="./viewtopic.php?f=28&amp;p=140964&amp;sid=32e897f27680334ea0085fb7ace65864#p140964"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
		<tr>
			<td class="row1" width="50" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
			<td class="row1" width="100%">
				
				<a class="forumlink" href="./viewforum.php?f=29&amp;sid=32e897f27680334ea0085fb7ace65864">Прочее в Поволжском регионе</a>
				<p class="forumdesc">Прочее и всякое</p>
				
					<p class="forumdesc"><strong>Модераторы:</strong> <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3163&amp;sid=32e897f27680334ea0085fb7ace65864">Валерий</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3649&amp;sid=32e897f27680334ea0085fb7ace65864">Андрей_СПб</a></p>
				
			</td>
			<td class="row2" align="center"><p class="topicdetails">35</p></td>
			<td class="row2" align="center"><p class="topicdetails">447</p></td>
			<td class="row2" align="center" nowrap="nowrap">
				
					<p class="topicdetails">Ср окт 15, 2014 22:19</p>
					<p class="topicdetails"><a href="./memberlist.php?mode=viewprofile&amp;u=16353&amp;sid=32e897f27680334ea0085fb7ace65864">Dog</a>
						<a href="./viewtopic.php?f=29&amp;p=142061&amp;sid=32e897f27680334ea0085fb7ace65864#p142061"><img src="./styles/subsilver2/imageset/icon_topic_latest.gif" width="18" height="9" alt="Перейти к последнему сообщению" title="Перейти к последнему сообщению" /></a>
					</p>
				
			</td>
		</tr>
	
</table>
<span class="gensmall"><a href="./ucp.php?mode=delete_cookies&amp;sid=32e897f27680334ea0085fb7ace65864">Удалить cookies конференции</a> | <a href="./memberlist.php?mode=leaders&amp;sid=32e897f27680334ea0085fb7ace65864">Наша команда</a></span><br />


<br clear="all" />

<table class="tablebg" width="100%" cellspacing="1" cellpadding="0" style="margin-top: 5px;">
	<tr>
		<td class="row1">
			<p class="breadcrumbs"><a href="./index.php?sid=32e897f27680334ea0085fb7ace65864">Список форумов</a></p>
			<p class="datetime">Часовой пояс: UTC + 3 часа [ Летнее время ]</p>
		</td>
	</tr>
	</table>
	<br clear="all" />

	<table class="tablebg" width="100%" cellspacing="1">
	<tr>
		<td class="cat" colspan="2"><h4>Кто сейчас на конференции</h4></td>
	</tr>
	<tr>
	
		<td class="row1" rowspan="2" align="center" valign="middle"><img src="./styles/subsilver2/theme/images/whosonline.gif" alt="Кто сейчас на конференции" /></td>
	
		<td class="row1" width="100%"><span class="genmed">Всего посетителей: <strong>83</strong>, из них зарегистрированных: 18, скрытых: 0 и гостей: 65 (основано на активности пользователей за последние 5 минут)<br />Больше всего посетителей (<strong>193</strong>) здесь было Вт сен 23, 2014 19:58<br /><br />Зарегистрированные пользователи: <a href="./memberlist.php?mode=viewprofile&amp;u=24&amp;sid=32e897f27680334ea0085fb7ace65864">Alex(Scar)</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=9216&amp;sid=32e897f27680334ea0085fb7ace65864">Andrzej</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=4953&amp;sid=32e897f27680334ea0085fb7ace65864">Bambr 11</a>, <span style="color: #9E8DA7;" class="username-coloured">Bing [Bot]</span>, <a href="./memberlist.php?mode=viewprofile&amp;u=17111&amp;sid=32e897f27680334ea0085fb7ace65864">borgia1</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=16407&amp;sid=32e897f27680334ea0085fb7ace65864">failbot</a>, <span style="color: #9E8DA7;" class="username-coloured">Google [Bot]</span>, <a href="./memberlist.php?mode=viewprofile&amp;u=9260&amp;sid=32e897f27680334ea0085fb7ace65864">Iskander</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=11727&amp;sid=32e897f27680334ea0085fb7ace65864">NikSamara</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=10065&amp;sid=32e897f27680334ea0085fb7ace65864">nobody</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=17604&amp;sid=32e897f27680334ea0085fb7ace65864">predsedatel7</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=16524&amp;sid=32e897f27680334ea0085fb7ace65864">taranuho.a</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=3282&amp;sid=32e897f27680334ea0085fb7ace65864">Vinny M</a>, <span style="color: #9E8DA7;" class="username-coloured">Yandex [Bot]</span>, <a href="./memberlist.php?mode=viewprofile&amp;u=9352&amp;sid=32e897f27680334ea0085fb7ace65864">кинолог</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=17185&amp;sid=32e897f27680334ea0085fb7ace65864">Лёха Лёха</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=5&amp;sid=32e897f27680334ea0085fb7ace65864" style="color: #AA0000;" class="username-coloured">Михалыч</a>, <a href="./memberlist.php?mode=viewprofile&amp;u=8791&amp;sid=32e897f27680334ea0085fb7ace65864">Чечако</a></span></td>
	</tr>
	
		<tr>
			<td class="row1"><b class="gensmall">Легенда :: <a style="color:#AA0000" href="./memberlist.php?mode=group&amp;g=4054&amp;sid=32e897f27680334ea0085fb7ace65864">Администраторы</a>, <a style="color:#00AA00" href="./memberlist.php?mode=group&amp;g=4053&amp;sid=32e897f27680334ea0085fb7ace65864">Супермодераторы</a></b></td>
		</tr>
	
	</table>

	<br clear="all" />

	<table class="tablebg" width="100%" cellspacing="1">
	<tr>
		<td class="cat" colspan="2"><h4>Дни рождения</h4></td>
	</tr>
	<tr>
		<td class="row1" align="center" valign="middle"><img src="./styles/subsilver2/theme/images/whosonline.gif" alt="Дни рождения" /></td>
		<td class="row1" width="100%"><p class="genmed">Сегодня нет дней рождения.</p></td>
	</tr>
	</table>


<br clear="all" />

<table class="tablebg" width="100%" cellspacing="1">
<tr>
	<td class="cat" colspan="2"><h4>Статистика</h4></td>
</tr>
<tr>
	<td class="row1"><img src="./styles/subsilver2/theme/images/whosonline.gif" alt="Статистика" /></td>
	<td class="row1" width="100%" valign="middle"><p class="genmed">Всего сообщений: <strong>133834</strong> | Тем: <strong>5572</strong> | Пользователей: <strong>4872</strong> | Новый пользователь: <strong><a href="./memberlist.php?mode=viewprofile&amp;u=17854&amp;sid=32e897f27680334ea0085fb7ace65864">Nina777</a></strong></p></td>
</tr>
</table>


	<br clear="all" />

	<form method="post" action="./ucp.php?mode=login&amp;sid=32e897f27680334ea0085fb7ace65864">

	<table class="tablebg" width="100%" cellspacing="1">
	<tr>
		<td class="cat"><h4><a href="./ucp.php?mode=login&amp;sid=32e897f27680334ea0085fb7ace65864">Вход</a></h4></td>
	</tr>
	<tr>
		<td class="row1" align="center"><span class="genmed">Имя пользователя:</span> <input class="post" type="text" name="username" size="10" />&nbsp; <span class="genmed">Пароль:</span> <input class="post" type="password" name="password" size="10" />&nbsp;  <span class="gensmall">Автоматически входить при каждом посещении</span> <input type="checkbox" class="radio" name="autologin" />&nbsp; <input type="submit" class="btnmain" name="login" value="Вход" /></td>
	</tr>
	</table>
	<input type="hidden" name="redirect" value="./index.php?sid=32e897f27680334ea0085fb7ace65864" />

	
	</form>


<br clear="all" />

<table class="legend">
<tr>
	<td width="20" align="center"><img src="./styles/subsilver2/imageset/forum_unread.gif" width="46" height="25" alt="Непрочитанные сообщения" title="Непрочитанные сообщения" /></td>
	<td><span class="gensmall">Непрочитанные сообщения</span></td>
	<td>&nbsp;&nbsp;</td>
	<td width="20" align="center"><img src="./styles/subsilver2/imageset/forum_read.gif" width="46" height="25" alt="Нет непрочитанных сообщений" title="Нет непрочитанных сообщений" /></td>
	<td><span class="gensmall">Нет непрочитанных сообщений</span></td>
	<td>&nbsp;&nbsp;</td>
	<td width="20" align="center"><img src="./styles/subsilver2/imageset/forum_read_locked.gif" width="46" height="25" alt="Нет непрочитанных сообщений [ Тема закрыта ]" title="Нет непрочитанных сообщений [ Тема закрыта ]" /></td>
	<td><span class="gensmall">Форум закрыт</span></td>
</tr>
</table>


</div>

<div id="wrapfooter">
	
	<span class="copyright">Создано на основе <a href="https://www.phpbb.com/">phpBB</a>&reg; Forum Software &copy; phpBB Group
	<br /><a href='http://www.phpbbguru.net/'>Русская поддержка phpBB</a></span>
</div>

<br /><a href="http://forum.fonarevka.ru"><img title="Фонарёвка: Независимый форум" src="http://fonarevka.ru/minilogo_forum.jpg" alt="Фонарёвка: всё о фонарях" border="0"></a><div class="copyright" style="margin-top: 5px;">Объявления <a href="http://www.lithiumstudios.org/">Advertisement Management</a>. Перевод от <a href="http://fladex.ru/">FladeX</a>.</div><!-- Yandex.Metrika informer -->
<a href="http://metrika.yandex.ru/stat/?id=11787436&amp;from=informer"
target="_blank" rel="nofollow"><img src="//bs.yandex.ru/informer/11787436/3_1_FFFFFFFF_FFFFFFFF_0_pageviews"
style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" /></a>
<!-- /Yandex.Metrika informer --><!-- Yandex.Metrika counter -->
<div style="display:none;"><script type="text/javascript">
(function(w, c) {
(w[c] = w[c] || []).push(function() {
try {
w.yaCounter11787436 = new Ya.Metrika({id:11787436, enableAll: true, webvisor:true});
}
catch(e) { }
});
})(window, "yandex_metrika_callbacks");
</script></div>
<script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript" defer="defer"></script>
<noscript><div><img src="//mc.yandex.ru/watch/11787436" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
</body>
</html>